spring:
  cloud:
    gateway:
      routes:
      - id: test
        uri: http://localhost:8081
        predicates:
        - Path=/test/**
        filters:
        - StripPrefix= 1
        - AddRequestHeader= authentication, token
